---
- name: "update local apt repo."
  necome: true 
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt: 
    upgrade: yes


- name: "remove stale dependencies"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies[node.js and npm]"
  become: true
  apt: 
    name: ["node.js", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present